# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Enable Mapbox
$RNMapboxMapsImpl = 'mapbox'

target 'mobile' do
  config = use_native_modules!
  
  # 🔥 BẮT BUỘC: static frameworks cho Firebase + gRPC
  use_frameworks! :linkage => :static
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # ⬇️ THÊM FIREBASE PODS VÀO ĐÂY ⬇️
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  # ⬆️ KẾT THÚC PHẦN THÊM ⬆️
  
  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end
  
  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end